### ISSUE TITLE
Documentation fails to build

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#1204]
**Describe the bug**
Been failing for a while. I've done a bisect and determined it's part of the memory footprinting that's causing the failure . This is where I am so far:

5f6a86986 -broken
0aba5c12b -broken
13b2bb99 -broken
3ce7ad61a -broken
3fb84390f -broken
ec6b2793a -?
dca8cd780 -working
fd29fe74f -working

**Comment by lifflander** [comment]
```
Traceback (most recent call last):
  File "./m.css/documentation/doxygen.py", line 3859, in <module>
    run(state, templates=os.path.abspath(args.templates), wildcard=args.wildcard, index_pages=args.index_pages, search_merge_subtrees=not args.search_no_subtree_merging, search_add_lookahead_barriers=not args.search_no_lookahead_barriers, search_merge_prefixes=not args.search_no_prefix_merging)
  File "./m.css/documentation/doxygen.py", line 3766, in run
    data = build_search_data(state, add_lookahead_barriers=search_add_lookahead_barriers, merge_subtrees=search_merge_subtrees, merge_prefixes=search_merge_prefixes)
  File "./m.css/documentation/doxygen.py", line 2440, in build_search_data
    return serialize_search_data(trie, map, search_type_map, symbol_count, merge_subtrees=merge_subtrees, merge_prefixes=merge_prefixes)
  File "/build/vt/m.css/documentation/_search.py", line 428, in serialize_search_data
    serialized_trie = trie.serialize(merge_subtrees=merge_subtrees)
  File "/build/vt/m.css/documentation/_search.py", line 391, in serialize
    self.root_offset_struct.pack_into(output, 0, self._serialize(hashtable, output, merge_subtrees=merge_subtrees))
  File "/build/vt/m.css/documentation/_search.py", line 345, in _serialize
    offset = child[1]._serialize(hashtable, output, merge_subtrees=merge_subtrees)
  File "/build/vt/m.css/documentation/_search.py", line 345, in _serialize
    offset = child[1]._serialize(hashtable, output, merge_subtrees=merge_subtrees)
  File "/build/vt/m.css/documentation/_search.py", line 345, in _serialize
    offset = child[1]._serialize(hashtable, output, merge_subtrees=merge_subtrees)
  [Previous line repeated 6 more times]
  File "/build/vt/m.css/documentation/_search.py", line 356, in _serialize
    assert len(self.children) < 16 and len(self.results) < 2048
AssertionError
```

**Comment by cz4rs** [comment]
for the record, link to the issue created in `m.css`:
https://github.com/mosra/m.css/issues/190
