### ISSUE TITLE
Azure pipeline 'gcc-7, ubuntu, mpich, trace runtime, LB' failes to compile vt

### ISSUE THREAD

**Issue by jstrzebonski** [DARMA-tasking/vt#1615]
Probably it's because of insufficient disk space.

```
##[error]System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at Microsoft.VisualStudio.Services.Agent.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at Microsoft.VisualStudio.Services.Agent.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at Microsoft.VisualStudio.Services.Agent.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at Microsoft.VisualStudio.Services.Agent.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at Microsoft.VisualStudio.Services.Agent.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at Microsoft.VisualStudio.Services.Agent.Tracing.Error(Exception exception)
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.MainAsync(IHostContext context, String[] args)
Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at Microsoft.VisualStudio.Services.Agent.TraceManager.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.Services.Agent.TraceManager.Dispose()
   at Microsoft.VisualStudio.Services.Agent.HostContext.Dispose(Boolean disposing)
   at Microsoft.VisualStudio.Services.Agent.HostContext.Dispose()
   at Microsoft.VisualStudio.Services.Agent.Worker.Program.Main(String[] args)
,##[error]We stopped hearing from agent vt-scale-0000JE. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
Pool: vt-agent-pool
Agent: vt-scale-0000JE
Started: Today at 12:54 AM
Duration: 43m 16s
```

**Comment by PhilMiller** [comment]
This one uses unity builds, which makes ccache pretty much useless. So, we could jettison one or the other and probably gain some space back.

There's plenty of opportunities in the scripts to delete things once they're no longer useful. It'll just be tedious to implement.

I wish we could just run on instances with more disk space.

**Comment by cz4rs** [comment]
I'm getting following error:
```
##[error]We stopped hearing from agent Azure Pipelines 11. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
Agent: Azure Pipelines 11
Started: Yesterday at 6:00 PM
Duration: 49m 52s
```
(for example [here](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=26424&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3).

**Comment by cz4rs** [comment]
@jstrzebonski 
With `VT_UNITY_BUILD: 0`:
```
##[error]Unhandled exception. System.IO.IOException: No space left on device
```
Details: [build logs](https://dev.azure.com/DARMA-tasking/DARMA/_build/results?buildId=26511&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3).
