### ISSUE TITLE
TestIntegralSet.test_interval_set_2 crashes in IntegralSetBase::joinRight

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/vt#486]
**Describe the bug**

`TestIntegralSet.test_interval_set_2` terminates with the error:
```
free(): invalid size: 0x00007fffffffb1a0
```
as a result of trying to execute `set_.erase(next)` at `src/vt/termination/interval/integral_set.h:359` when `next eq set_.end()`.

This happens when `tests/unit/termination/test_integral_set.cc:120` calls `i.insert(k);` with `k=0` on a previously-empty `IntegralSet`.

A partial backtrace is below:
```
#0  vt::term::interval::IntegralSetBase<int, 0, std::allocator, vt::term::interval::Interval, std::set, vt::term::interval::IntervalCompare>::joinRight (
    this=0x7fffffffb140, it=...)
    at vt/src/vt/termination/interval/integral_set.h:359
#1  0x0000000000447a30 in vt::term::interval::IntegralSetBase<int, 0, std::allocator, vt::term::interval::Interval, std::set, vt::term::interval::IntervalCompare>::join (this=0x7fffffffb140, it=...)
    at vt/src/vt/termination/interval/integral_set.h:336
#2  0x000000000044585a in vt::term::interval::IntegralSetBase<int, 0, std::allocator, vt::term::interval::Interval, std::set, vt::term::interval::IntervalCompare>::insertSet(std::_Rb_tree_const_iterator<vt::term::interval::Interval<int, 0> >, vt::term::interval::Interval<int, 0>&&) (this=0x7fffffffb140, it=..., 
    i=<unknown type in vt-build/tests/test_integral_set, CU 0xac971, DIE 0x168e4f>)
    at vt/src/vt/termination/interval/integral_set.h:281
#3  0x0000000000443724 in vt::term::interval::IntegralSetBase<int, 0, std::allocator, vt::term::interval::Interval, std::set, vt::term::interval::IntervalCompare>::insertInterval<vt::term::interval::Interval<int, 0>, void>(vt::term::interval::Interval<int, 0>&&) (this=0x7fffffffb140, 
    i=<unknown type in vt-build/tests/test_integral_set, CU 0xac971, DIE 0x169e4d>)
    at vt/src/vt/termination/interval/integral_set.h:150
#4  0x00000000004419e2 in vt::term::interval::IntegralSetBase<int, 0, std::allocator, vt::term::interval::Interval, std::set, vt::term::interval::IntervalCompare>::insert<int&, void> (this=0x7fffffffb140, val=@0x7fffffffb138: 0)
    at vt/src/vt/termination/interval/integral_set.h:113
#5  0x000000000043d3fc in vt::tests::unit::TestIntegralSet_test_interval_set_2_Test::TestBody (this=0xbac7e0)
    at vt/tests/unit/termination/test_integral_set.cc:120
```

**To Reproduce**

Execute `mpirun -np 1 ./tests/test_integral_set --gtest_filter="TestIntegralSet.test_interval_set_2"`

The test fails for me on Kahuna using gcc 8.2.0.

**To Fix**

I think that `src/vt/termination/interval/integral_set.h:356` should read `if (next not_eq set_.end()) {` instead of `if (it not_eq set_.end()) {`.

@lifflander @PhilMiller - Do you agree with the proposed fix?

**Comment by lifflander** [comment]
Merged, closing
