### ISSUE TITLE
Fix bug in "vt:*/TestTermDepSendChain.test_term_dep_send_chain/*_proc_2"

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/vt#694]
**Describe the bug**
On `develop`, `vt:*/TestTermDepSendChain.test_term_dep_send_chain/*_proc_2` has been failing occasionally. A bug must have been introduced recently.

Here's an example failure:

https://github.com/DARMA-tasking/vt/runs/451407453

**Comment by lifflander** [comment]
I'm now able to reproduce this with the docker ubuntu trace + LB build. I have a RelWithDebugInfo build successfully reproducing the bug.

Stack trace:

```
#0  vt::term::ds::TermDS<vt::term::ds::StateDS>::tryLast (this=this@entry=0x5586bcb28410) at /usr/src/vt/src/vt/termination/dijkstra-scholten/ds.cc:314
314        C = ackedParent = ackedArbitrary = reqedParent = 0;
(gdb) bt
#0  vt::term::ds::TermDS<vt::term::ds::StateDS>::tryLast (this=this@entry=0x5586bcb28410) at /usr/src/vt/src/vt/termination/dijkstra-scholten/ds.cc:314
#1  0x00005586bad688c3 in vt::term::ds::TermDS<vt::term::ds::StateDS>::msgProcessed (this=0x5586bcb28410, predecessor=<optimized out>, count=<optimized out>) at /usr/src/vt/src/vt/termination/dijkstra-scholten/ds.cc:213
#2  0x00005586bad0e73d in vt::term::TerminationDetector::produceConsume (this=this@entry=0x5586bc9a9cf0, epoch=<optimized out>, num_units=<optimized out>, num_units@entry=1, produce=<optimized out>, produce@entry=false,
    node=<optimized out>) at /usr/src/vt/src/vt/termination/termination.cc:244
#3  0x00005586bac45c7d in vt::term::TerminationDetector::consume (node=<optimized out>, num_units=1, epoch=<optimized out>, this=0x5586bc9a9cf0) at /usr/src/vt/src/vt/termination/termination.impl.h:67
#4  vt::messaging::PendingSend vt::vrt::collection::CollectionManager::sendMsgUntypedHandler<vt::tests::unit::MyCol::OpMsg, vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> >(vt::vrt::collection::VrtElmProxy<vt::tests::unit::MyCol, vt::tests::unit::MyCol::IndexType> const&, vt::tests::unit::MyCol::OpMsg*, long const&, bool, bool)::{lambda(vt::messaging::MsgSharedPtr<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> >)#1}::operator()(vt::messaging::MsgSharedPtr<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> >) const::{lambda()#1}::operator()() const (__closure=0x5586bc9c1c30) at /usr/src/vt/src/vt/vrt/collection/manager.impl.h:1489
#5  std::_Function_handler<void (), vt::messaging::PendingSend vt::vrt::collection::CollectionManager::sendMsgUntypedHandler<vt::tests::unit::MyCol::OpMsg, vt::tests::unit::MyCol, vt::index::DenseIndexArray<int, (signed char)2> >(vt::vrt::collection::VrtElmProxy<vt::tests::unit::MyCol, vt::tests::unit::MyCol::IndexType> const&, vt::tests::unit::MyCol::OpMsg*, long const&, bool, bool)::{lambda(vt::messaging::MsgSharedPtr<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> >)#1}::operator()(vt::messaging::MsgSharedPtr<vt::messaging::ActiveMsg<vt::messaging::ActiveEnvelope> >) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#6  0x00005586bae8d0ae in std::function<void ()>::operator()() const (this=0x7ffc3b84fb90) at /usr/include/c++/7/bits/std_function.h:706
#7  vt::sched::PriorityUnit::execute (this=0x7ffc3b84fb90) at /usr/src/vt/src/vt/scheduler/prioritized_work_unit.h:63
#8  vt::sched::PriorityUnit::operator() (this=0x7ffc3b84fb90) at /usr/src/vt/src/vt/scheduler/prioritized_work_unit.h:59
#9  vt::sched::Scheduler::runNextUnit (this=this@entry=0x5586bc9ad0d0) at /usr/src/vt/src/vt/scheduler/scheduler.cc:94
#10 0x00005586bae8d374 in vt::sched::Scheduler::scheduler (this=0x5586bc9ad0d0, msg_only=msg_only@entry=false) at /usr/src/vt/src/vt/scheduler/scheduler.cc:220
#11 0x00005586bae8d487 in vt::runScheduler () at /usr/src/vt/src/vt/scheduler/scheduler.cc:272
#12 0x00005586bab6fd35 in vt::tests::unit::MyObjGroup::finishUpdate (this=0x5586bc9e8af0) at /usr/src/vt/tests/unit/termination/test_term_dep_send_chain.cc:418
#13 vt::tests::unit::TestTermDepSendChain_test_term_dep_send_chain_Test::TestBody (this=<optimized out>) at
```

The issue is that cleanup seems to be removing a pointer to a `TermDS` that is needed. I'm not sure why its not recreating it (which would also be a silent bug) or why a message comes in later with that epoch once it calls `rootTerminated`. I thought this could be a reentrancy problem, but I can't figure out how that's happening from the valgrind logs.

Also, I was able to get valgrind to show an invalid write even when the bug is silent and the program appears to terminate normally.
